### ISSUE TITLE
Can't reach bottom of modal with backdrop

### ISSUE THREAD

**Issue by alexlya** [codidact/co-design#10]
It's not possible to reach the bottom of the modal with backdrop in a small browser window:

![image](https://user-images.githubusercontent.com/23587065/72279567-5030ea80-362e-11ea-945f-ec59f139d64b.png)

**Comment by luap42** [comment]
Oops, that shouldn't happen.

What might work is adding this CSS to the modal wrapper (`.modal`) when with backdrop:

```css
.modal.is-with-backdrop {
    overflow: auto;
    max-height: 100%;
}
```

I'll look into it later, when I have some time, or tomorrow.
