### ISSUE TITLE
Add different font stacks for different languages

### ISSUE THREAD

**Issue by MoshiKoi** [codidact/co-design#46]
See also: https://github.com/codidact/qpixel/issues/270

Shouldn't be a too difficult addition, just need to add something like

```scss
$language-fonts: {
  "he": "frank ruhl libre", "narkisim", serif !default; // Hebrew
  // etc.
}
```
```scss
@each $key, $value in $language-fonts {
  [lang=$key] {
    font-family: $value;
  }
}
```

(Disclaimer: I'm not familiar with SCSS but this should give a general idea)
