### ISSUE TITLE
Some syntax error in CoDesign 

### ISSUE THREAD

**Issue by Istiakshovon** [codidact/co-design#61]
When I opened CoDesign in VS Code. I found some syntax error.

```css
&.is-#{$i}\%, {
                width: $i * 1%;
}
```

Error : Selector expressed.

There shouldn't be comma. The above error is showing for that comma. Since, I am working on CoDesign. So, I am thinking to fix those error. Should I? Or, Should I leave as it is? Maybe those syntax error don't affect other code. But, it's not looking good to me when I am seeing error in VS Code.
